### PR TITLE
Prepare for 2.1.4

### PR DESCRIPTION
**Pull request by aharpervc**
#### todo

- [x] public prerelease incorporating these with assistance from @bvogelzang & co
  - [x] https://github.com/rails-sqlserver/tiny_tds/pull/475
  - [x] https://github.com/rails-sqlserver/tiny_tds/pull/481
  - [ ] ~https://github.com/rails-sqlserver/tiny_tds/pull/469~ (later)
- [x] get feedback on this prerelease and/or those PR's
- [x] merge the PR's
- [x] update the changelog here
- [x] update to 2.1.4 final here
- [ ] merge this PR
- [ ] public release

### CODE REVIEW

**Comment by aharpervc** [comment]
Updated to `pre2` with the `false` fix, cc @bvogelzang @wpolicarpo. One of us will cut a new release shortly. BTW I took the liberty of squashing your PR's down to a single commit just for this preview branch only; each one can merge to master with whatever is the appropriate number of commits.

**Comment by swatosh** [comment]
Would it be possible to update the embedded version of OpenSSL in the mingw32 versions before the official release? Thanks!

(If not, is it as simple as overwriting the dlls and exe in the bin folder? Or are there instructions somewhere that I failed to find?)

For the silent majority: Thank you for this gem, it's been fantastic!

**Comment by aharpervc** [comment]
> Would it be possible to update the embedded version of OpenSSL in the mingw32 versions before the official release? Thanks!
> 
> (If not, is it as simple as overwriting the dlls and exe in the bin folder? Or are there instructions somewhere that I failed to find?)
> 
> For the silent majority: Thank you for this gem, it's been fantastic!

My preference is to avoid anything else that would extend the timeframe for getting this release out. We can always cut a new version with new changes once they are all approved.

Is something broken with OpenSSL right now? Is there already an issue or PR tracking this request? (If not, can you make it?)

**Comment by swatosh** [comment]
> > Would it be possible to update the embedded version of OpenSSL in the mingw32 versions before the official release? Thanks!
> > (If not, is it as simple as overwriting the dlls and exe in the bin folder? Or are there instructions somewhere that I failed to find?)
> > For the silent majority: Thank you for this gem, it's been fantastic!
> 
> My preference is to avoid anything else that would extend the timeframe for getting this release out. We can always cut a new version with new changes once they are all approved.
> 
> Is something broken with OpenSSL right now? Is there already an issue or PR tracking this request? (If not, can you make it?)

There are two CVEs in OpenSSL 1.1.1j that our security folks are on about. No PR that I know of. I can try, but I don't really have any kind of development environment, so it'll be iffy.

**Comment by swatosh** [comment]
> > > Would it be possible to update the embedded version of OpenSSL in the mingw32 versions before the official release? Thanks!
> > > (If not, is it as simple as overwriting the dlls and exe in the bin folder? Or are there instructions somewhere that I failed to find?)
> > > For the silent majority: Thank you for this gem, it's been fantastic!
> > 
> > 
> > My preference is to avoid anything else that would extend the timeframe for getting this release out. We can always cut a new version with new changes once they are all approved.
> > Is something broken with OpenSSL right now? Is there already an issue or PR tracking this request? (If not, can you make it?)
> 
> There are two CVEs in OpenSSL 1.1.1j that our security folks are on about. No PR that I know of. I can try, but I don't really have any kind of development environment, so it'll be iffy.

So I created a PR. Seems trivial, but as I mentioned, I don't really have a development environment. Hope it's near what's needed

**Pull request merged**
