### PR TITLE
Add ruby 2.3 to appveyor config

### PR DESCRIPTION
**Pull request by aharpervc**
expecting this to work per https://www.appveyor.com/docs/installed-software#ruby

### CODE REVIEW

**Comment by aharpervc** [comment]
Is there an intentional reason ruby 2.1 isn't on the list?

**Comment by metaskills** [comment]
Testing all the rubies made for super slow tests and feedback. I picked what felt reasonable.

**Comment by metaskills** [comment]
My thinking was Ruby 2.0 was the bottom... and that 2.1 was not that different between 2.0 or 2.2 and one or the other would catch 2.1 in some way. Hope that makes sense.

**Comment by aharpervc** [comment]
I see. I don't know much about appveyor... maybe there's a way to do a "lightweight" test on just 1 ruby (latest version), then separately/manually a "full" test on all supported rubies?

**Comment by metaskills** [comment]
Well, what we are testing is talking to different SQL Server versions. The matrix of all ruby versions to all SQL Server versions has diminishing returns. I'd like to keep the test on the bare minimum of Ruby versions to get that done. To that end, can this PR remove `ruby_version: "22"`?

**Comment by aharpervc** [comment]
I get it, so the concept is to just put the min/max versions, not all intermediate versions

**Comment by metaskills** [comment]
Merging... seems the branch merge tests have not been passing on Appveyor lately for some reason. Will watch master build now and look at the other PR.

**Comment by aharpervc** [comment]
Sweet

**Pull request merged**
