### PR TITLE
Openssl 1.1.0

### PR DESCRIPTION
**Pull request by orgads**
See discussion on https://github.com/rails-sqlserver/tiny_tds/issues/310 and previous PR https://github.com/rails-sqlserver/tiny_tds/pull/344 by @metaskills.

### CODE REVIEW

**Comment by orgads** [comment]
Ok, this perl installation just doesn't work in this environment. Is there a way to grab another perl?

**Comment by metaskills** [comment]
Love the DDL rename commit. 

> this perl installation just doesn't work in this environment

What does the OpenSSL team use on their Appveyor builds? This would help isolate if our `C:\MinGW\msys\1.0\bin` is still leaking issues.

**Comment by orgads** [comment]
The problem is not AppVeyor, but the Ruby devkit. It is prepend to PATH, and users perl from mSYS1. This will be a problem with local builds as well.

I see 2 options:
# Download perl as part of openssl installing, and force using it (like I did here with C:\Perl, only that it will be in the build directory)
# Wait for rubyinstaller2, and drop support for devkit.

I prefer the first option.

The question is how do we fetch perl? Maybe from MSYS2? Do you have an idea?

**Comment by metaskills** [comment]
I don't since this is not my speciality. cc @coderjoe

**Comment by orgads** [comment]
Ok, this perl just doesn't work for openssl. I guess we have no choice but to install msys2.

**Comment by orgads** [comment]
... Or use Git's! :)

**Comment by orgads** [comment]
Finally a link problem! 64 but compiles. I'll look into it later.

**Comment by orgads** [comment]
Woohoo! :)

**Comment by metaskills** [comment]
Amazing Work. Thanks! I'd like to hold off on this till #345 is done. I see some git conflicts, but that can be worked out. 

In the meantime, I used this branch locally to build and publish `v1.2.0.beta1` and pushed those gems to rubygems.org. I'm going to solicit others to test it out. Again, thanks!!!

**Comment by orgads** [comment]
My pleasure :)

**Comment by metaskills** [comment]
@coderjoe What do you think of merging this in and coping with the rebase in #345? I think it would be cool to get a 1.2.0 version out that is confirmed working better on Windows.

**Comment by coderjoe** [comment]
A hearty :+1:. The rebase shouldn't be too much trouble at all. It sounds worth it.

**Pull request merged**
