### PR TITLE
Use OpenSSL v1.1.0e & FreeTDS v1.00.27

### PR DESCRIPTION
**Pull request by metaskills**

### CODE REVIEW

**Comment by metaskills** [comment]
Right now I am trying to figure out how to get the right Perl path in place. When we do `SET PATH=C:\MinGW\msys\1.0\bin;%PATH%` it puts an older version of Perl in the path. That can be fixed by doing `SET PATH=C:\Perl\bin;%PATH%` below it. And the `perl --version ` show the correct 5.22. However, MiniPortile still fails below because it finds that previous version. Any ideas on how to help? My Questions are:

* Just a gut check, but is adding `C:\MinGW\msys\1.0\bin` right? Should we do something else?
* Depending on that answer, how do we get `rake compile` to see the right version?
* Maybe this work should happen after #345 now?

**Comment by YvesR** [comment]
You are trying this in a windows environment?
I am still working with docker image rake-compiler where freetds build failed as described. Do you fail earlier with your perl problem or later (means you can build freetds)?

**Comment by metaskills** [comment]
> You are trying this in a windows environment?

I am trying to make all the CI builds first. Ubuntu seemed to work pretty easily. Focus is on Appveyor. That usually gives me a good signal to move onward to local rake compiler work.

**Comment by orgads** [comment]
I'm also trying to build it (locally for now). Will post my own PR if I succeed.

**Comment by metaskills** [comment]
Pull Request #347 pulled in OpenSSL v1.1.0 and we got new versions of TinyTDS at v1.2.0 which should solve this issue. Please reply back and let us know.

**Pull request closed without merging**
