### PR TITLE
Upgrade to freetds-1.00

### PR DESCRIPTION
**Pull request by aharpervc**
Still trying to get my test environment working... but hypothetically this is all that's necessary

### CODE REVIEW

**Comment by aharpervc** [comment]
Hm... something's definitely busted... looking into it

**Comment by aharpervc** [comment]
Looks like it can't find the freetds header file(s), or at least sybfront.h

```
have_header: checking for sybfront.h... -------------------- no

"i686-w64-mingw32-gcc -o conftest.exe -I/usr/local/rake-compiler/ruby/i686-w64-mingw32/ruby-2.3.0/include/ruby-2.3.0/i386-mingw32 -I/usr/local/rake-compiler/ruby/i686-w64-mingw32/ruby-2.3.0/include/ruby-2.3.0/ruby/backward -I/usr/local/rake-compiler/ruby/i686-w64-mingw32/ruby-2.3.0/include/ruby-2.3.0 -I../../../../ext/tiny_tds -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64  -s -O1 -fno-omit-frame-pointer -fno-fast-math  conftest.c  -L. -L/usr/local/rake-compiler/ruby/i686-w64-mingw32/ruby-2.3.0/lib      -lmsvcrt-ruby230  -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi   "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: int main(int argc, char **argv)
6: {
7:   return 0;
8: }
/* end */

"i686-w64-mingw32-gcc -E -I/usr/local/rake-compiler/ruby/i686-w64-mingw32/ruby-2.3.0/include/ruby-2.3.0/i386-mingw32 -I/usr/local/rake-compiler/ruby/i686-w64-mingw32/ruby-2.3.0/include/ruby-2.3.0/ruby/backward -I/usr/local/rake-compiler/ruby/i686-w64-mingw32/ruby-2.3.0/include/ruby-2.3.0 -I../../../../ext/tiny_tds -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64  -s -O1 -fno-omit-frame-pointer -fno-fast-math   conftest.c -o conftest.i"
conftest.c:5:22: fatal error: sybfront.h: No such file or directory
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: #include <sybfront.h>
/* end */

--------------------

```

**Comment by aharpervc** [comment]
oops, forgot the patch file.

**Comment by metaskills** [comment]
Hmmm... not sure why Azure tests are giving that host error.

**Comment by metaskills** [comment]
Installing FreeTDS 1.00 now to test it out. Will report back.

**Comment by metaskills** [comment]
Tests were all green on my end, let me see how this works in master.

**Comment by metaskills** [comment]
All green in master. Thanks!!!

**Comment by aharpervc** [comment]
sweet

**Pull request merged**
