### PR TITLE
Default FreeTDS to 0.95. Support 0.91 Alternate.

### PR DESCRIPTION
**Pull request by metaskills**
This work was started by Lars Kanis <lars@greiz-reinsdorf.de>
Comments below are his from initial #232 pull request.

> I'm more or less finished with the build part of this issue. The AppVeyor results are not clean, but I'm less experienced with MSSQL, so it's maybe better if you (@metaskills) could have a look at it. I noticed two small issues with FreeTDS, to which I opened a PR for:
> 
> * https://github.com/FreeTDS/freetds/pull/25
> * https://github.com/FreeTDS/freetds/pull/26
> 
> The `0001-mingw_missing_inet_pton.diff` in the initial work does not have a FreeTDS pull request. I think it is too special to the RubyInstaller environment (DevKit-4.7.2) and no worth a PR in FreeTDS.

### CODE REVIEW

**Comment by metaskills** [comment]
@larskanis Could you please work in this local branch vs fork and pull request? It would really help me both rebase and contribute to it while we sort out the details of the failing tests.

**Comment by metaskills** [comment]
These are the failing tests I will be working on. https://gist.github.com/metaskills/7ad5b4fd5d4a1944272c

**Comment by larskanis** [comment]
@metaskills The new patch files from PR #232 are missing, aren't they?

So I should directly commit to this branch? Do I have commit rights?

**Comment by metaskills** [comment]
> So I should directly commit to this branch? Do I have commit rights?

Wow... was fairly certain I added those. So yes, please do! You are added as a collaborator.

**Comment by metaskills** [comment]
I just did a rebase to master and force pushed to this branch.

**Comment by metaskills** [comment]
@larskanis I have pushed the patches you mentioned (you as author) and am going to work on getting 0.95 tests passing.

**Comment by metaskills** [comment]
I just did a rebase to master and force push to this branch.

**Comment by metaskills** [comment]
OK, I spent a few days on this and it is going to take awhile. As you can see in the commits I am doubling down on this move and making v7.3 the default TDS version too since v1.0 of TinyTDS will be compiled with 0.95 (or maybe 0.99) by default. Here is a summary of the pain point we not sit.

There is something subtly wrong with either current FreeTDS or TinyTDS's message/error handler. When sh*t happens, the connection becomes un-usable. The 3 tests in [the gist](https://gist.github.com/metaskills/7ad5b4fd5d4a1944272c) above are our canary. This [gist](https://gist.github.com/metaskills/c726ecd31affa3f3b639) shows how I was testing `tsql` under the same situations to make sure it was not a FreeTDS bug. In that gist you can see how I am using `TDSDUMP` to get some low level debug info. Looking at that debug info is my next step. As well as trying to test a very recent 0.95.65 too.

**Comment by larskanis** [comment]
Both above PR's on FreeTDS got merged, that's why [this patch file](https://github.com/rails-sqlserver/tiny_tds/commit/24e981713300192eb4c9b7f80906c7462e3e1dd5) is obsolete with FreeTDS-0.95.65.

Regarding the message/error handler, I'm currently too busy to have a look at it. Possibly an issue caused by [this change](https://github.com/rails-sqlserver/tiny_tds/commit/2bcc1b73ec088f2b20f6fdc0c201be030982d380#diff-97d2fee337d72b6db90a5c416070486cL97) ?

**Comment by metaskills** [comment]
Thanks @larskanis I'll make some adjustments and report back.

**Comment by metaskills** [comment]
> Both above PR's on FreeTDS got merged, that's why this patch file is obsolete with FreeTDS-0.95.65.

Thanks! Commit 4ca8dc3 removes the patch as mentioned here. http://git.io/vl8hY and I pushed our constants to use 0.95.65 too. Force push update too.

> Regarding the message/error handler, I'm currently too busy to have a look at it. Possibly an issue caused by [this change](https://github.com/rails-sqlserver/tiny_tds/commit/2bcc1b73ec088f2b20f6fdc0c201be030982d380#diff-97d2fee337d72b6db90a5c416070486cL97)?

Nope, that's not it. I confirmed by doing a local revert. Same gist issues are still present :( would love a hand here. Please feel free to commit to this branch too. I may head on to some other things.

**Comment by metaskills** [comment]
:point_up: Is an issue on FreeTDS' GitHub repo. I also made a cross post to the mailing list.

**Comment by metaskills** [comment]
Good news, the blocker for 0.95 is a regression. See this [thread on FreeTDS' archives](http://lists.ibiblio.org/pipermail/freetds/2015q4/029621.html). The main quotes from Frediano

> Really interesting. Looks like the cancel is not sent directly but queued and later sent after the query. This make the query fail. Looks like the cancellation is not processed correctly for some reason. I'll have a look at what happen in the program.
> 
> Got it! Is not the cancel after the query but the cancel from the message handler. In this case a cancel is set but not reset causing it to be registered for the next query. Not hard to fix, time to write a new test (or extend another)
> 
> Being a regression it will be addresses on next 0.95.xx version too.

**Comment by metaskills** [comment]
@larskanis Did you see this post I made? http://technology.customink.dev/blog/2015/10/19/microsofts-first-open-source-datacamp/

**Comment by metaskills** [comment]
OK, this commit https://github.com/FreeTDS/freetds/commit/e45121425921cfa112a4323545a5af9ee22b61c4 fixes the issue with the connection not being usable after an invalid statement message canceling. :tada: :tada: :tada: There is only one more test that fails. This looks like another 0.95 regression. 

Our `must error gracefully from writing non-convertible characters` fails because the buffer seems to become corrupt. See this TDSDUMP below.

```
dblib.c:1338:dbcmd(0x7fca058a4f60, INSERT INTO [datatypes] ([nvarchar_50]) VALUES ('Test âœ“'))
dblib.c:1344:dbcmd() bufsz = 56
dblib.c:5845:dbfreebuf(0x7fca058a4f60)
dblib.c:6817:dbsqlsend(0x7fca058a4f60)
mem.c:648:tds_free_all_results()
util.c:165:Changed query state from IDLE to WRITING
util.c:322:tdserror(0x7fca046f4a80, 0x7fca044b0240, 2402, 0)
dblib.c:7897:dbperror(0x7fca058a4f60, 2402, 0)
dblib.c:7965:dbperror: Calling dblib_err_handler with msgno = 2402; msg->msgtext = "Error converting characters into server's character set. Some character(s) could not be converted"
dblib.c:5743:dbgetuserdata(0x7fca058a4f60)
dblib.c:5845:dbfreebuf(0x7fca058a4f60)
dblib.c:5743:dbgetuserdata(0x7fca058a4f60)
dblib.c:1338:dbcmd(0x7fca058a4f60, SELECT 1 AS [one])
dblib.c:1344:dbcmd() bufsz = 0
dblib.c:6817:dbsqlsend(0x7fca058a4f60)
util.c:165:Changed query state from WRITING to PENDING
packet.c:740:Sending packet
0000 01 01 00 56 00 00 01 00-16 00 00 00 12 00 00 00 |...V.... ........|
0010 02 00 01 00 00 00 33 00-00 00 01 00 00 00 16 00 |......3. ........|
0020 00 00 12 00 00 00 02 00-01 00 00 00 33 00 00 00 |........ ....3...|
0030 01 00 00 00 53 00 45 00-4c 00 45 00 43 00 54 00 |....S.E. L.E.C.T.|
0040 20 00 31 00 20 00 41 00-53 00 20 00 5b 00 6f 00 | .1. .A. S. .[.o.|
0050 6e 00 65 00 5d 00      -                        |n.e.].|
```

I will followup with FreeTDS again.

**Comment by larskanis** [comment]
@metaskills You even mentioned me in your blog post? Thanks!

Great, that you and freddy77 could solve the cancel issue.

**Comment by metaskills** [comment]
I just pushed up a commit that switches us to MSDBLIB structures. I wonder if this [ctlib header check](https://github.com/rails-sqlserver/tiny_tds/blob/master/ext/tiny_tds/extconf.rb#L285) is still needed tho. Not sure where that came from.

**Comment by metaskills** [comment]
@larskanis Of course I mentioned you! You have been a huge help here. I could not have done this without you.

**Comment by metaskills** [comment]
WRT 2008 data types [date], [datetime2], [datetimeoffset], and [time]. I created a new thread on FreeTDS' list. The new one is titled [Compiling Against FreeTDS 0.95 w/7.3 TDSVER Features Possible?](http://lists.ibiblio.org/pipermail/freetds/2015q4/thread.html) and should show up in the archives soon. Till then, here is a gist of the message. https://gist.github.com/metaskills/cdba73aa2488786a79d4

For academic reasons, here is the thread I started back in 2011, [2008 Data Types For DBLIB](http://lists.ibiblio.org/pipermail/freetds/2011q3/027209.html). It has some interesting replies and now that we are on 7.3, I am still unsure what functions I use to finally crack that data open.

**Comment by metaskills** [comment]
cc @saurabh500 for the comment above :point_up:

**Comment by saurabh500** [comment]
@metaskills I will go through the links and respond soon.

**Comment by metaskills** [comment]
@larskanis I though I had added you as a collaborator before. Just fixed that now.

**Comment by metaskills** [comment]
@saurabh500 the reply to my [thread](http://lists.ibiblio.org/pipermail/freetds/2015q4/029633.html) so far is:

> The binary structure is well defined (and an ABI actually) however is 
> defined in tds.h (TDS_DATETIMEALL). The date field is the same as 
> dtdays in DATETIME however 
> time is completely different (100-nanosecondth from start of day). 
> 
> dbdatecrack only supports DATETIME. I suppose a new dbanydatecrack (or whatever) 
> extension could be defined (possibly extending time precision). Or in 
> the meantime you could pass date field into a DATETIME, use 
> dbdatecrack and split time manually (at least the precision). 

I'd like to ask @freddy77 for some extension to be defined so we could use these types. But would love you feedback and possibly even if someone there could contribute to that. Assuming @freddy77 is OK with that. 

Lastly, this issue on FreeTDS (https://github.com/FreeTDS/freetds/issues/32) is the only true blocker to upgrading to 0.95. Not sure if anyone can make and submit a patch.

**Comment by saurabh500** [comment]
@metaskills 

In SqlClient for .Net we add the new supported types in the Tds Parser itself. 
The TdsParser for .Net has the byte identifier for the datatypes mentioned here
https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/TdsEnums.cs

Using these byte types we take a decision in the TdsParser about the incoming data from the server.
The following is the link to the line showing the Date and related artifacts parsing logic in the TdsParser.

https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/TdsParser.cs#L4457

**Comment by saurabh500** [comment]
Ideally FreeTDS should be able to expose these datatypes.

When you say extensions, what do you mean here? Do you mean extension for plugging in new Sql Datatypes into the parser so that datatypes can be supported without explicitly modifying the FreeTDS code?

**Comment by saurabh500** [comment]
@metaskills Does FreeTDS offer the binary data stream coming from the server, outside its implementation so that it can be consumed? Can you tell me where I can look at the APIs?

**Comment by metaskills** [comment]
> Does FreeTDS offer the binary data stream coming from the server, outside its implementation so that it can be consumed?

I believe so. Here is a gist of a [debug patch to this branch](https://gist.github.com/metaskills/d242807328f0f6436076) that demos adding a new data type to result case statement. In both cases, these fall thru to Ruby string method which would show the binary data as a string. This diff also has commented out tests we have had waiting for this day to come. Here is the output below.

```
$ rake test TESTOPTS="--name=/.*2008\ and\ up.*/"

  1) Failure:
Casting SQL Server schema::for 2008 and up#test_0003_casts datetime2:
--- expected
+++ actual
@@ -1 +1 @@
-""
+"\u0000\u0018SR$\u0000\u0000\u0000\xEFw\u0000\u0000\u0000\u0000\a`"

  2) Failure:
Casting SQL Server schema::for 2008 and up#test_0001_casts date:
--- expected
+++ actual
@@ -1 +1 @@
-""
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\xA5j\xF5\xFF\u0000\u0000\u0000@"

  3) Failure:
Casting SQL Server schema::for 2008 and up#test_0002_casts time:
--- expected
+++ actual
@@ -1 +1 @@
-""
+"\xA1\xEC\xD6\u0003\x84\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\a "

  4) Failure:
Casting SQL Server schema::for 2008 and up#test_0004_casts datetimeoffset:
--- expected
+++ actual
@@ -1 +1 @@
-""
+"\u0000Xv`g\u0000\u0000\u0000\xEFw\u0000\u0000 \xFE\u0002\xE0"
```

> Can you tell me where I can look at the APIs?

I think I can. This gem relies heavily on the DBLIB interface exposed in FreeTDS' sybdb.h file. See here for the 0.95 version https://github.com/FreeTDS/freetds/blob/Branch-0_95/include/sybdb.h Thanks in advance!

**Comment by metaskills** [comment]
@larskanis Would you mind looking at why the Windows build is failing now? Feel free to push changes to this branch.

**Comment by larskanis** [comment]
@metaskills I'll check this.

**Comment by metaskills** [comment]
OK, I pushed two more changes:

1) Skipping the test for `writing non-convertable characters` till I hear more from this https://github.com/FreeTDS/freetds/issues/32 It will allow us to get good CI feedback on this branch.
2) Default to TDSVER 7.1. @saurabh500 I may consider opening another issue for 2008 datatypes. But please keep posting here when you find more info.

**Comment by metaskills** [comment]
This is now the issue to track the new data types. https://github.com/rails-sqlserver/tiny_tds/issues/244

**Comment by metaskills** [comment]
THIS IS NOW IN MASTER!!!

**Comment by meet-bhagdev** [comment]
SO COOL!! WOOT WOOT KEN

**Comment by TigerMint** [comment]
YAYAYAYAYAYAY

**Comment by metaskills** [comment]
Huge thanks to @larskanis he pushed this forward too, without the Windows support which also included two patches to FreeTDS, it would not have happened.

**Pull request merged**
