### PR TITLE
Remove old Ruby version from CI config & cross build rake task

### PR DESCRIPTION
**Pull request by aharpervc**
This is a prerequisite for https://github.com/rails-sqlserver/tiny_tds/issues/434 (per [comment](https://github.com/rails-sqlserver/tiny_tds/issues/434#issuecomment-485863370)). It's effectively a followup to https://github.com/rails-sqlserver/tiny_tds/pull/428.

Adding recent contributors for review.

### CODE REVIEW

**Comment by aharpervc** [comment]
@larskanis looks like you were also doing this work here: https://github.com/rails-sqlserver/tiny_tds/compare/master...larskanis:update-windows-binary, was there a blocker on that?

**Comment by jrgns** [comment]
Can we perhaps add support for Ruby 2.7 while we're at it?

**Comment by aharpervc** [comment]
> Can we perhaps add support for Ruby 2.7 while we're at it?

I don't see why not

**Comment by larskanis** [comment]
@aharpervc I don't remember what interrupted me. Nevertheless you need to update rake-compiler-dock to 1.0 in order to cross build for Ruby-2.7. OpenSSL-1.1.1 should work as well. We cross build it in ruby-pg.

**Comment by larskanis** [comment]
Appveyor seems to be disabled for this repository. The badge icon in the README shows the last build two years ago.

**Comment by aharpervc** [comment]
Great @larskanis thanks for the tip. I removed the old appveyor config and updated rake-compiler-dock & the default OpenSSL version.

**Comment by aharpervc** [comment]
The 2.7 job is failing because tiny tds can't find the freetds headers (I think...) indicated by this right before the final error:

```log
checking for sybfront.h... no
checking for sybdb.h... no
checking for tdsdbopen() in -lsybdb... no
checking for dbanydatecrack() in -lsybdb... no
```

However, I don't know why that would be. Freetds appears to install without problem, and diffing the 2.6 & 2.7 job logs that part of each job seems to be similar. @larskanis ideas?

**Comment by aharpervc** [comment]
Given that 2.7 is requires additional changes, I'm going to slice that work out to another branch so we can get the other changes merged.

**Comment by larskanis** [comment]
@aharpervc Couldn't you reactivate Appveyor-CI instead of dropping it? That would make sure, that the gem is properly working on Windows. Or is there a particular reason to not use Appveyor any longer?

**Comment by aharpervc** [comment]
> Or is there a particular reason to not use Appveyor any longer?

I feel like I asked this question somewhere on this repo a long time ago, and there was an answer, but I can't recall what it was & I can't find my question.

I'm open to adding more CI config, especially for Windows. Whether that would be back to appveyor or some other service is an open question to me. Travis has Windows support now I believe, and CircielCI supports Linux/macOS/Windows and might be a better choice overall. Github Actions can be used for CI and also supports all the OS's.

**Comment by MadsNielsen** [comment]
Hey @aharpervc is there any change we might soon see a new release of this gem with the support for 2.6 and precompiled windows gems?

**Comment by aharpervc** [comment]
I hope so, although this branch has been superseded by https://github.com/rails-sqlserver/tiny_tds/pull/456

**Pull request merged**
