### PR TITLE
Adds a simple_username option for case where azure is true but you don't want user@domain

### PR DESCRIPTION
**Pull request by austra**

### CODE REVIEW

**Comment by austra** [comment]
This was an issue with an out of date freetds, appears to be resolved after updating from freetds 0.95 to 1.0

**Comment by metaskills** [comment]
Thanks for the PR and followup!

**Comment by austra** [comment]
We ended up needing this after all.  It looks like it might be the same issue as #288  (or at least the[ hijacked issue](https://github.com/rails-sqlserver/tiny_tds/issues/288#issuecomment-232682509) )

**Comment by metaskills** [comment]
@austra Can you elaborate a bit more, linked articles, etc on how and when using Azure does not enforce that username format?

**Comment by anderscarling** [comment]
If I remembwr correctly this would be functionally equivalent of running the new `:contained` option added in #292

**Comment by austra** [comment]
Just getting back around on this, thanks @anderscarling , you are correct.

**Pull request closed without merging**
