### PR TITLE
Move message_handler from a shared value to userdata

### PR DESCRIPTION
**Pull request by aharpervc**
- previously, subsequent instantiations of a client object would overwrite the message handler with their reference, causing messages to be handled by the latest client only
- now, the shared property is removed and each client object receives their own messages

### CODE REVIEW

**Comment by aharpervc** [comment]
Pretty sure the CircleCi failure is unrelated.

**Comment by aharpervc** [comment]
@metaskills ptal. Also, are you wanting a test that specifically covers this multi client case? It can be done (similar to the program in #400) it'll just be pretty large & awkward to cover something that's relatively hard to re-break in the future.

**Comment by aharpervc** [comment]
> I have a question. Would it make any difference if you called to_proc on the Method objects returned from the method call? Not familiar with passing those objects around. That said, I'm thinking it would still be the same outcome?

I do not believe this would be a relevant change, as the apparent problem isn't the kind of object, but that there was a shared value that shouldn't be shared.

**Comment by aharpervc** [comment]
Would you be willing to cut a new rubygems release for this? It'd be great to get out asap.

**Comment by metaskills** [comment]
Sure, just built and pushed v2.1.1 to rubygems.

**Comment by aharpervc** [comment]
💯 thanks

**Comment by metaskills** [comment]
Heads up @aharpervc. I created rails-sqlserver to an org and want to add you to this team for new access control. https://github.com/orgs/rails-sqlserver/teams/contributors

**Pull request merged**
