### PR TITLE
Add patch for getopt

### PR DESCRIPTION
**Pull request by l8nite**
I was trying to get the latest to install on alpine linux, stole this from http://git.alpinelinux.org/cgit/aports/tree/main/freetds/fix-includes.patch

### CODE REVIEW

**Comment by larskanis** [comment]
Wouldn't it be better to open a pull request on freetds? The patches in tiny_tds are usually only applied for issues, that are very specific to the environment in which tiny_tds is typically used (like the old gcc/mingw version of the RubyInstaller's Devkit).

**Comment by l8nite** [comment]
@freddy77 what do you think?

**Comment by metaskills** [comment]
Correct, the patches are there to primarily support our efforts to precompile static libs. They are only ever used when FreeTDS is not installed on your system via some package manager. For example, I use MacPorts and there may be a few patches we do for our platform, TinyTDS should not assume that, I think your package manager and/or relationship to the parent project, in this case FreeTDS should. Could you open an issue on http://github.com/FreeTDS/freetds and link it to here?

**Comment by l8nite** [comment]
Thanks guys, I've opened https://github.com/FreeTDS/freetds/issues/45

**Pull request closed without merging**
