### PR TITLE
Replace rb_thread_blocking_region (removed in Ruby 2.2.0) w/ rb_thread_c...

### PR DESCRIPTION
**Pull request by rushed**

### CODE REVIEW

**Comment by dougjohnston** [comment]
:+1:

**Comment by rhettbarber** [comment]
+1  :thumbsup:

**Comment by saltracer** [comment]
:+1:

**Comment by metaskills** [comment]
Still working on the adapter :+1:

**Comment by pisaruk** [comment]
+1  :thumbsup:

**Comment by saltracer** [comment]
@metaskills Thanks for all of your hard work on this (and other) projects. I am able to use and enjoy Rails because of your efforts over the years on the SQLServer interfacing ensuring a high quality experience.

**Comment by metaskills** [comment]
Merged, all tests passed in 1.9.3, 2.1, and 2.2 for me.

**Comment by daveramachandran** [comment]
I am seeing the same error, but I can see this has been resolved in 0.6.3. I have 0.6.2 currently installed, but unable to find this latest 0.6.3 version. How do I get this version.?

**Comment by rushed** [comment]
@daveramachandran you might wait until "gem list --remote tiny_tds" shows 0.6.3 or later has been released, or if you're brave: gem 'tiny_tds', github: 'rails-sqlserver/tiny_tds'

**Comment by haslo** [comment]
Thanks a lot for this fix! Saved us loads of trouble!

Any idea when 0.6.3 will be released? We're currently using the master in our gemfile, but would love to be able to revert to regular versioning...

**Comment by metaskills** [comment]
> Any idea when 0.6.3 will be released?

No, but you can bundle to the repo now if you want.

**Comment by haslo** [comment]
> > Any idea when 0.6.3 will be released?

> No, but you can bundle to the repo now if you want.

Thanks :+1: That's what we're doing, works perfectly fine, we'd just prefer not having to link to any repos :blush:

**Pull request merged**
