### PR TITLE
Prepare for v2.1.3

### PR DESCRIPTION
**Pull request by aharpervc**
Now, need to remember how to build & push these gems correctly.

This will close https://github.com/rails-sqlserver/tiny_tds/issues/458 & https://github.com/rails-sqlserver/tiny_tds/issues/434 when I merge & push the final release

### CODE REVIEW

**Comment by aharpervc** [comment]
Welp it looks like at least Travis is rebuilding master every time I push to this branch, which is super lame, so I guess I'll look at that configuration now.

**Comment by aharpervc** [comment]
I have pushed `2.1.3-pre` to rubygems for testing

**Comment by aharpervc** [comment]
I will move the openssl change out of this branch before merging. If nobody has any other objections I will try to merge & push v2.1.3 final next week.

**Comment by swatosh** [comment]
Thanks for the nudge to report! We tested 2.1.3-pre with ruby 2.5.5 and
2.6.5 and rails 5.2.4.2 at work and we are all green. (Not that this tells
you much, but I suppose it's better than nothing)

**Comment by ecentell-CPF** [comment]
Do you know when v2.1.3 final might be pushed?  Thanks!

**Comment by aharpervc** [comment]
The next step is to slice out that openssl url change to a separate PR, get that merged, then rebase this branch & remove the `-pre`. Then it can be merged, and then I can build & push the gems.

**Comment by ecentell-CPF** [comment]
Can you provide an update @aharpervc thanks!

**Comment by aharpervc** [comment]
> Can you provide an update @aharpervc thanks!

The current status is that this is blocked on https://github.com/rails-sqlserver/tiny_tds/issues/465, as I said. I don't want to ship a broken gem, so figuring out what is going on there is a prerequisite for shipping. Anyone can contribute to that investigation, so if getting 2.1.3 deployed is a priority for you, then any assistance you can provide to resolving the blocking issue will help make that happen.

**Comment by aharpervc** [comment]
I foolishly published the Linux version to rubygems before building the Windows version, but of course now I'm having a problem building it 🤦‍♂️. I am investigating, and hopefully all versions will be published soon

For posterity, this is the current error:

```
$ bundle exec rake gem:windows
(...snip...)
Running 'compile' for libiconv 1.15... ERROR, review '/tmp/tmp/i686-w64-mingw32/ports/libiconv/1.15/compile.log' to see what happened. Last lines are:
========================================================================
libtool: install: .
libtool: install: .
libtool: install: .
libtool: install: .
libtool: install: .
libtool: install: .
libtool: install: .
libtool: install: .
libtool: install: .
libtool: install: https://stackoverflow.com/questions/27784961/received-warning-message-path-set-to-rvm-after-updating-ruby-version-using-rvm
libtool: install: ../bin/libcharset-1.dll
/usr/bin/install: target '../bin/libcharset-1.dll' is not a directory
Makefile:82: recipe for target 'install-lib' failed
```

That's a new one for me...

**Comment by aharpervc** [comment]
This is almost certainly a path problem when building from Windows hosts, but with help from @bvogelzang all copies are now pushed to rubygems

**Pull request merged**
