### PR TITLE
 Use official HTTP mirrors instead of FTP for 1-stable

### PR DESCRIPTION
**Pull request by januszm**
Related PR: https://github.com/rails-sqlserver/tiny_tds/pull/384

Change FreeTDS source server from FTP to HTTP

### CODE REVIEW

**Comment by januszm** [comment]
It'd be great if one of the maintainers could have a look at failing specs. Looks like the test MSSQL server is not available?

**Comment by wpolicarpo** [comment]
@metaskills can you have a look here? I'm not sure if you want maintain `1.3.x` given you decided to remove `freetds` installation from the gem itself (which I agree).

**Comment by aharpervc** [comment]
The http archive goes down all the time as well, unfortunately (doesn't mean we shouldn't merge this, just fyi)

**Comment by januszm** [comment]
Can't we upload source files to a more reliable cloud storage or CDN? (e.g. Amazon S3, CloudFront) ?

**Comment by wpolicarpo** [comment]
We can, but there are many problems with this approach:

1. Security: How to guarantee the integrity of downloaded file if we host it somewhere?
2. Cost: After all, someone would need to pay for it.
3. Maintainers would have to monitor/maintain another source of artifacts

I personally don't see any issues in merging this, but I don't think it will solve the main issue, which is managing external dependencies and probably that's why they changed it in 2.x.

In my opinion, installing `freetds` should be a step of your deploy. It's more secure and reliable if we do that by ourselves than delegating this to a gem installation.

**Comment by januszm** [comment]
@wpolicarpo 

> In my opinion, installing `freetds` should be a step of your deploy. It's more secure and reliable if we do that by ourselves than delegating this to a gem installation.

I can not agree more, but it's not always easily available on certain Linux distributions, and this mechanism of downloading and installing `freetds` is just a nice "emergency" mechanism.

This still does not seem like a fully reliable solution, but, you know what they say: "something is better than nothing".

**Comment by andyundso** [comment]
appears to be the same change as in #384.

**Comment by andyundso** [comment]
ah I see it targets v1 instead of `main`. don't think we support this version anymore.

**Comment by januszm** [comment]
It's fine, for Amazon Linux I found a better solution, however it requires some manual maintenance, maybe once a year. For those who are interested, it's all about compiling FreeTDS on an Amazon Linux X (e.g. 2023), packaging it as zip or tar.gz and hosting on S3 bucket. It can be then downloaded fast (same Amazon Data Center ideally) and extracted to target system:

```
commands:
  install_freetds:
    command: |
      aws s3 cp s3://YOUR_S3_BUCKET_HERE/freetds-al2023/freetds.tar.bz2 freetds.tar.bz2
      tar xfo freetds.tar.bz2 -C /usr/
      mv /usr/etc/{freetds.conf,locales.conf,pool.conf} /etc/
```

**Pull request closed without merging**
