### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aharpervc**
- documented the :message_handler option with example

### CODE REVIEW

**Comment by aharpervc** [comment]
@metaskills forgot this from the main PR... any concerns?

**Comment by metaskills** [comment]
Merged! :)

**Comment by aharpervc** [comment]
💯 now just eagerly awaiting 2.1.0 final release.........

**Comment by metaskills** [comment]
It'll happen this weekend. I'm doing some major fixes in the adapter too so it'll be a great weekend.

**Pull request merged**
