### PR TITLE
FreeTDS: Link libgcc statically

### LINKED ISSUE #349: Undefined method connect for TinyTds::Client In Windows
I 'm trying to install tiny_tds in my windows machine.

This is the result I get when I `tsql -C `
```
[TinyTds][v1.1.0][tsql]: C:/Ruby22/lib/ruby/gems/2.2.0/gems/tiny_tds-1.1.0-x86-
ingw32/exe/tsql.EXE
```

This is the error message I get when I try executing  
`TinyTds::Client.new(username: "xx", password: "xxx", host: "xxxx", database: "xxxxxx")
`

 ```

NoMethodError: undefined method `connect' for #<TinyTds::Client:0x2eda828>
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/tiny_tds-1.1.0-x86-mingw32/lib/t
iny_tds/client.rb:53:in `initialize'
        from (irb):12:in `new'
        from (irb):12
        from C:/Ruby22/bin/irb:11:in `<main>'

```

### PR DESCRIPTION
**Pull request by orgads**
Fixes #349

### CODE REVIEW

**Comment by orgads** [comment]
Ok, I built it and can confirm it solves the issue.

**Comment by orgads** [comment]
Ah, wait. It works with devkit but not with rake-compiler-dock. Let me do some more tests.

**Comment by orgads** [comment]
Ok, now it works both on cross-compilation and on devkit.

I tried many ways to pass the flags without overriding the CC variable, but couldn't. See [This thread](https://www.mail-archive.com/mingw-w64-public@lists.sourceforge.net/msg09680.html) for another user that faced this problem...

**Comment by metaskills** [comment]
I'll try this out tonight. If it works, do we think a 1.2.1 release with it?

**Comment by aharpervc** [comment]
FWIW I manually built the gem with this patch, and things seem to work okay for me 👍

**Comment by metaskills** [comment]
Thanks! I just pushed v1.3.0 to rubygems.

**Pull request merged**
