### PR TITLE
FreeTDS 1.0

### PR DESCRIPTION
**Pull request by metaskills**

### CODE REVIEW

**Comment by metaskills** [comment]
@larskanis Can you take a look at this branch. Trying to get FreeTDS 1.0rc1 built on Windows. Not sure, but I think this is the error?

```
sspi.c: In function 'tds_sspi_get_auth':
sspi.c:258:20: error: 'AI_V4MAPPED' undeclared (first use in this function)
```

**Comment by larskanis** [comment]
@metaskills I tested with sspi enabled. See here: https://github.com/FreeTDS/freetds/pull/61

**Comment by metaskills** [comment]
Thanks @larskanis I just tried 1.0rc2 and it failed with the same message. Do you think it has something to do with the `0001-mingw_missing_inet_pton` patch or the move to `1.0.2g` of OpenSSL during this work?

**Comment by larskanis** [comment]
@metaskills The patches are not yet included in 1.0rc2. Let's wait for rc3.

**Comment by metaskills** [comment]
Thanks @larskanis, I wanted to get a bit faster feedback, so I [included a patch](https://github.com/rails-sqlserver/tiny_tds/pull/265/commits/68bd9ee6f2bbb71f6db0b61a9682f05e028c3d21) that had your two commits. And I still got an error on Appveyor. See https://gist.github.com/metaskills/15ca7c5503947bf5821eb9d517835295

**Comment by metaskills** [comment]
We are all green on Appveyor!

**Comment by aharpervc** [comment]
:tada: :balloon: :100:

**Pull request merged**
