### PR TITLE
Pin CI to Ubuntu 22.04

### PR DESCRIPTION
**Pull request by andyundso**
Microsoft SQL Server 2017 will not work on Ubuntu 24.04.

### CODE REVIEW

**Comment by aharpervc** [comment]
For the `n`th time, remind me why we're unable to run tests on the stock container images?

**Comment by andyundso** [comment]
we are using the Stock container images, but something with the SQL Server 2017 image is broken on Ubuntu 24.04 (I assume the old 18.04 Kernel of SQL Server 2017 image does not work with newer distros).

**Comment by aidanharan** [comment]
It may be related to https://github.com/microsoft/mssql-docker/issues/899

**Comment by andyundso** [comment]
we only install on Windows, as there we do not have container images available. on Linux, we use containers (see e.g. [here](https://github.com/rails-sqlserver/tiny_tds/actions/runs/11446915491/job/31847282989), just need to open the part which says "Setup MSSQL" and there you see the `docker pull` logs).

**Comment by aharpervc** [comment]
Ah, I see potatoqualitee/mssqlsuite is running the linux image as you said, when possible

**Pull request merged**
